<?php

namespace App\Livewire\Casos;

use App\Helpers\Helpers;
use App\Livewire\BaseComponent;
use App\Models\Bank;
use App\Models\Caso;
use App\Models\CasoEstado;
use App\Models\Currency;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Livewire\Attributes\Computed;
use Livewire\Attributes\On;
use Livewire\Attributes\Url;
use Livewire\WithFileUploads;
use Livewire\WithPagination;

class CasoManager extends BaseComponent
{
  use WithFileUploads, WithPagination;

  // ====== Parámetros de tabla/listado ======
  #[Url(history: true)] public $search = '';
  #[Url(history: true)] public $active = '';
  #[Url(history: true)] public $sortBy = 'casos.created_at';
  #[Url(history: true)] public $sortDir = 'DESC';
  #[Url()] public $perPage = 10;

  public $action = 'list';
  public $recordId = '';
  public $closeForm = false;
  public $columns;
  public $defaultColumns;

  public $document_type = 'CASO';

  // ====== Catálogos/auxiliares ======
  public $banks      = [];
  public $currencies = [];
  public $abogados   = [];
  public $asistentes = [];
  public $estados    = [];
  public $productos  = [];
  public $procesos   = [];
  public $clientes   = [];
  public $expectativas   = [];

  // =========  TODAS LAS COLUMNAS DE la tabla `casos`  =========
  public $id,
    $pnumero,
    $contact_id,
    $bank_id,
    $product_id,
    $proceso_id,
    $currency_id,
    $pnombre_apellidos_deudor,
    $pcedula_deudor,
    $psaldo_dolarizado,
    $psaldo_de_seguros,
    $psaldo_de_multas,
    $pfecha_pago_multas_y_seguros,
    $pfecha_asignacion_caso,
    $abogado_id,
    $asistente1_id,
    $asistente2_id,
    $pnumero_operacion1,
    $pnumero_operacion2,
    $pnumero_contrato,
    $pnombre_demandado,
    $pnumero_cedula,
    $pnombre_arrendatario,
    $pcedula_arrendatario,
    $pcorreo_demandado_deudor_o_arrendatario,
    $ptelefono_demandado_deudor_o_arrendatario,
    $pnombre_contacto_o_arrendatario,
    $pnombre_coarrendatario,
    $pcedula_coarrendatario,
    $pcorreo_coarrendatario,
    $ptelefono_coarrendatario,
    $pdatos_codeudor1,
    $pdatos_codeudor2,
    $pdatos_anotantes,
    $pdetalle_garantia,
    $pubicacion_garantia,
    $pfecha_presentacion_demanda,
    $pdespacho_judicial_juzgado,
    $pnumero_expediente_judicial,
    $pmonto_estimacion_demanda,
    $pexpectativa_recuperacion_id,
    $pgastos_legales_caso,
    $pcomentarios_bullet_point,
    $pplaca1,
    $pplaca2,
    $pdepartamento_solicitante,
    $pfecha_e_instruccion_levantamiento,
    $pcontrato_leasing,
    $ptitular_contrato,
    $pcedula_titular,
    $pestatus_operacion,
    $ppoderdante_id,
    $pfecha_ingreso_cobro_judicial,
    $pfecha_escrito_demanda,
    $nfecha_traslado_juzgado,
    $nfecha_notificacion_todas_partes,
    $npartes_notificadas,
    $sfecha_captura,
    $sfecha_sentencia,
    $sfecha_remate,
    $sfecha_primer_remate,
    $sfecha_segundo_remate,
    $sfecha_tercer_remate,
    $afecha_aprobacion_remate,
    $afecha_protocolizacion,
    $afecha_senalamiento_puesta_posesion,
    $apuesta_posesion,
    $agastos_legales,
    $ahonorarios_totales,
    $anumero_placa1,
    $anumero_placa2,
    $acolisiones_embargos_anotaciones,
    $anumero_marchamo,
    $afirma_legal,
    $afecha_registro,
    $afecha_presentacion_protocolizacion,
    $afecha_inscripcion,
    $afecha_terminacion,
    $afecha_suspencion_arreglo,
    $ajustificacion_casos_protocolizados_embargo,
    $aestado_proceso_general_id,
    $afecha_informe_ultima_gestion,
    $atipo_expediente,
    $areasignaciones,
    $nmarchamo,
    $nanotaciones,
    $nubicacion_garantia,
    $ntalleres_situaciones,
    $nfecha_notificacion,
    $ncomentarios,
    $nhonorarios_notificacion,
    $nhonorarios_cobro_administrativo,
    $nexonerado_cobro,
    $nfecha_pago,
    $nestado_actual_primera_notificacion,
    $noposicion_demanda,
    $nfecha_audiencia,
    $ntipo_garantia,
    $nembargos_cuentas,
    $nembargos_salarios,
    $nembargos_muebles,
    $nembargos_inmuebles,
    $nestado_id,
    $afecha_aprobacion_arreglo,
    $acomentarios,
    $aregistro_pago,
    $afecha_envio_cotizacion_gasto,
    $atraspaso_tercero,
    $tfecha_traspaso,
    $thonorarios_traspaso,
    $tgastos_traspaso,
    $ttraspaso_favor_tercero,
    $tfecha_envio_borrador_escritura,
    $tborrador_escritura,
    $tfecha_firma_escritura,
    $tfecha_presentacion_escritura,
    $tfecha_comunicacion,
    $tautorizacion_tercero,
    $tfecha_entrega_titulo_propiedad,
    $tfecha_exclusion,
    $tfecha_terminacion,
    $tgastos_legales,
    $thonorarios_totales,
    $lasesoramiento_formal,
    $lfecha_entrega_poder,
    $lsumaria,
    $lcausa,
    $lfecha_levantamiento_gravamen,
    $lfecha_comunicado_banco,
    $lproveedores_servicio,
    $fhonorarios_levantamiento,
    $fcomision_ccc,
    $fhonorarios_totales,
    $efecha_visita,
    $egestion_a_realizar,
    $eestado_cliente_gran_tamano,
    $ranotacion,
    $rmarchamo_al_dia,
    $rpendiente,
    $rcausa,
    $rfecha_desinscripcion,
    $rhonorario_escritura_inscripcion,
    $rgastos_impuestos,
    $dnombre_notario,
    $dnumero_carnet,
    $dcorreo_electronico,
    $dnumero_telefonico,
    $destado_casos_con_anotaciones,
    $dfecha_interposicion_denuncia,
    $dnumero_expediente,
    $dresultado_sentencia,
    $dgastos_microfilm,
    $dhonorarios,
    $bapersonamiento_formal,
    $bfecha_entrega_poder,
    $bsumaria,
    $bcausa,
    $bfecha_levantamiento_gravamen,
    $bproveedores_servicios,
    $bgastos_proceso,
    $bhonorarios_levantamiento,
    $bhonorarios_comision,
    $bhonorarios_totales,
    $f1fecha_asignacion_capturador,
    $f1proveedor_servicio,
    $f1estado_captura,
    $f1honorarios_capturador,
    $f1honorarios_comision,
    $f2causa_remate,
    $f2publicacion_edicto,
    $f2fecha_publicacion_edicto,
    $f2tiempo_concedido_edicto,
    $f2preclusion_tiempo,
    $f2estado_remanente,
    $afecha_firmeza_aprobacion_remate,
    $abienes_adjudicados,
    $asaldo_capital_operacion,
    $aestimacion_demanda_en_presentacion,
    $abufete,
    $acarga_gastos_legales,
    $agastos_mas_honorarios_acumulados,
    $ahonorarios_iniciales,
    $adiferencia_demanda_presentada,
    $adiferencia_sentencia_afavor,
    $adiferencia_sentencia_enfirme,
    $adiferencia_liquidacion_de_sentencia_enfirme,
    $adiferencia_segunda_liquidacion_de_sentencia_enfirme,
    $adiferencia_tercera_liquidacion_de_sentencia_enfirme,
    $adiferencia_cuarta_liquidacion_de_sentencia_enfirme,
    $adiferencia_quinta_liquidacion_de_sentencia_enfirme,
    $adiferencia_sexta_liquidacion_de_sentencia_enfirme,
    $adiferencia_septima_liquidacion_de_sentencia_enfirme,
    $adiferencia_octava_liquidacion_de_sentencia_enfirme,
    $adiferencia_novena_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_primera_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_segunda_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_tercera_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_cuarta_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_quinta_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_sexta_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_septima_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_octava_liquidacion_de_sentencia_enfirme,
    $adiferencia_decima_novena_liquidacion_de_sentencia_enfirme,
    $agastos_legales_iniciales,
    $adiferencia_gastos_legales,
    $anumero_grupo,
    $ajuzgado,
    $aestado_operacion,
    $pretenciones,
    $pfecha_ultimo_giro,
    $nfecha_entrega_requerimiento_pago,
    $nfecha_entrega_orden_captura,
    $testado_proceso_id,
    $lestado_levantamiento_id,
    $bestado_levantamiento_id,
    $ddespacho_judicial_juzgado_id,
    $ldespacho_judicial_juzgado_id,
    $afecha_levantamiento,
    $pfecha_informe,
    $pnumero_tarjeta,
    $pnombre_persona_juridica,
    $pnumero_cedula_juridica,
    $pcomprador,
    $amonto_avaluo,
    $afecha_avaluo,
    $aembargo_cuentas,
    $aembargo_salarios,
    $aembargo_muebles,
    $aembargo_inmuebles,
    $aretenciones_con_giro,
    $afecha_ultimo_giro,
    $pmonto_estimacion_demanda_colones,
    $pmonto_estimacion_demanda_dolares,
    $pfecha_curso_demanda,
    $pfecha_primer_giro,
    $pmonto_retencion_colones,
    $pmonto_retencion_dolares,
    $pinmueble,
    $pvehiculo,
    $pente,
    $pmonto_prima,
    $pplazo_arreglo_pago,
    $pmonto_arreglo_pago,
    $pmonto_cuota,
    $pestado_arreglo,
    $pno_cuota,
    $pdatos_fiadores,
    $fecha_creacion,
    $psubsidiaria,
    $afecha_presentacion_embargo,
    $afecha_arreglo_pago,
    $afecha_pago,
    $amonto_cancelar,
    $amonto_incobrable,
    $acontacto_telefonico,
    $acorreo,
    $pmueble,
    $pestadoid,
    $ames_avance_judicial,
    $pavance_cronologico,
    $lavance_cronologico,
    $savance_cronologico,
    $aavance_cronologico,
    $f1avance_cronologico,
    $f2avance_cronologico,
    $navance_cronologico,
    $fecha_importacion,
    $nombre_cliente,
    $email_cliente,
    $nfecha_ultima_liquidacion,
    $fecha_activacion,
    $codigo_activacion,
    $user_create,
    $user_update,
    $pultima_gestion_cobro_administrativo,
    $pfecha_devolucion_demanda_firma,
    $estado_id,
    $asaldo_capital_operacion_usd,
    $aestimacion_demanda_en_presentacion_usd,
    $liquidacion_intereses_aprobada_crc,
    $liquidacion_intereses_aprobada_usd,
    $ahonorarios_totales_usd,
    $tiempo_dias,
    $tiempo_annos,
    $empresa,
    $fecha_inicio_retenciones,
    $fecha_prescripcion,
    $fecha_pruebas,
    $motivo_terminacion,
    $honorarios_legales_dolares,
    $created_at,
    $updated_at,
    $deleted_at;

  // ====== Config de validación por grupos (para crear reglas sin omitir nada) ======
  private $dateFields = [
    'pfecha_pago_multas_y_seguros',
    'pfecha_asignacion_caso',
    'pfecha_presentacion_demanda',
    'pfecha_ingreso_cobro_judicial',
    'pfecha_escrito_demanda',
    'nfecha_traslado_juzgado',
    'nfecha_notificacion_todas_partes',
    'sfecha_captura',
    'sfecha_sentencia',
    'sfecha_remate',
    'sfecha_primer_remate',
    'sfecha_segundo_remate',
    'sfecha_tercer_remate',
    'afecha_aprobacion_remate',
    'afecha_protocolizacion',
    'afecha_senalamiento_puesta_posesion',
    'afecha_registro',
    'afecha_presentacion_protocolizacion',
    'afecha_inscripcion',
    'afecha_terminacion',
    'afecha_suspencion_arreglo',
    'afecha_informe_ultima_gestion',
    'nfecha_notificacion',
    'nfecha_pago',
    'nfecha_audiencia',
    'afecha_aprobacion_arreglo',
    'afecha_envio_cotizacion_gasto',
    'tfecha_traspaso',
    'tfecha_envio_borrador_escritura',
    'tfecha_firma_escritura',
    'tfecha_presentacion_escritura',
    'tfecha_comunicacion',
    'tfecha_entrega_titulo_propiedad',
    'tfecha_exclusion',
    'tfecha_terminacion',
    'lfecha_entrega_poder',
    'lfecha_levantamiento_gravamen',
    'lfecha_comunicado_banco',
    'efecha_visita',
    'rfecha_desinscripcion',
    'dfecha_interposicion_denuncia',
    'bfecha_entrega_poder',
    'bfecha_levantamiento_gravamen',
    'f1fecha_asignacion_capturador',
    'f2fecha_publicacion_edicto',
    'afecha_firmeza_aprobacion_remate',
    'pfecha_ultimo_giro',
    'nfecha_entrega_requerimiento_pago',
    'nfecha_entrega_orden_captura',
    'afecha_levantamiento',
    'pfecha_informe',
    'afecha_avaluo',
    'afecha_ultimo_giro',
    'pfecha_curso_demanda',
    'pfecha_primer_giro',
    'fecha_creacion',
    'afecha_presentacion_embargo',
    'afecha_arreglo_pago',
    'afecha_pago',
    'fecha_importacion',
    'nfecha_ultima_liquidacion',
    'fecha_activacion',
    'pultima_gestion_cobro_administrativo',
    'pfecha_devolucion_demanda_firma',
    'fecha_inicio_retenciones',
    'fecha_prescripcion',
    'fecha_pruebas',
    'created_at',
    'updated_at',
    'deleted_at'
  ];

  private $varchar2Fields = [
    'apuesta_posesion',
    'nexonerado_cobro',
    'noposicion_demanda',
    'nembargos_cuentas',
    'nembargos_salarios',
    'nembargos_muebles',
    'nembargos_inmuebles',
    'abienes_adjudicados',
    'aembargo_cuentas',
    'aembargo_salarios',
    'aembargo_muebles',
    'aembargo_inmuebles',
    'ranotacion',
    'rmarchamo_al_dia',
    'rpendiente'
  ];

  private $varchar10Fields = ['nmarchamo', 'pestado_arreglo', 'codigo_activacion', 'tiempo_dias', 'tiempo_annos'];

  private $varchar30Fields = ['ptelefono_demandado_deudor_o_arrendatario', 'pplaca1', 'pplaca2', 'pnumero_cedula_juridica'];

  private $varchar50Fields = [
    'pcedula_deudor',
    'pcedula_arrendatario',
    'pcorreo_demandado_deudor_o_arrendatario',
    'dnumero_carnet',
    'dcorreo_electronico',
    'dnumero_telefonico',
    'anumero_placa1',
    'anumero_placa2',
    'anumero_marchamo',
    'atipo_expediente',
    'pnumero_operacion2',
    'pnumero_contrato',
    'pnumero_tarjeta',
    'acontacto_telefonico',
    'acorreo'
  ];

  private $varchar100Fields = [
    'pnombre_apellidos_deudor',
    'pnombre_arrendatario',
    'pnombre_contacto_o_arrendatario',
    'pnombre_coarrendatario',
    'pcedula_coarrendatario',
    'pcorreo_coarrendatario',
    'ptelefono_coarrendatario',
    'pnumero_cedula',
    'pdepartamento_solicitante',
    'pcontrato_leasing',
    'ptitular_contrato',
    'pcedula_titular',
    'pestatus_operacion',
    'afirma_legal',
    'areasignaciones',
    'nestado_actual_primera_notificacion',
    'ntipo_garantia',
    'f1proveedor_servicio',
    'f1estado_captura',
    'f2causa_remate',
    'f2publicacion_edicto',
    'f2tiempo_concedido_edicto',
    'f2preclusion_tiempo',
    'f2estado_remanente',
    'abufete',
    'ajuzgado',
    'aestado_operacion',
    'pnombre_persona_juridica',
    'pcomprador',
    'aretenciones_con_giro',
    'pente',
    'pplazo_arreglo_pago',
    'pno_cuota',
    'psubsidiaria',
    'pestadoid',
    'dnombre_notario',
    'destado_casos_con_anotaciones',
    'bapersonamiento_formal',
    'bsumaria',
    'bcausa',
    'bproveedores_servicios',
    'lasesoramiento_formal',
    'lsumaria',
    'lcausa',
    'lproveedores_servicio',
    'egestion_a_realizar',
    'eestado_cliente_gran_tamano',
    'asaldo_capital_operacion_usd',
    'aestimacion_demanda_en_presentacion_usd',
    'liquidacion_intereses_aprobada_crc',
    'liquidacion_intereses_aprobada_usd',
    'ahonorarios_totales_usd',
    'motivo_terminacion'
  ];

  private $varchar150Fields = ['nombre_cliente', 'empresa'];

  private $varchar160Fields = ['email_cliente'];

  private $varchar200Fields = [
    'psaldo_dolarizado',
    'pnumero_operacion1',
    'pnombre_demandado',
    'pnumero_expediente_judicial',
    'pmonto_estimacion_demanda',
    'pdatos_codeudor1',
    'pdatos_anotantes',
    'agastos_legales',
    'ahonorarios_totales',
    'asaldo_capital_operacion',
    'aestimacion_demanda_en_presentacion',
    'amonto_avaluo',
    'pmonto_estimacion_demanda_colones',
    'pmonto_estimacion_demanda_dolares',
    'pmonto_retencion_colones',
    'pmonto_retencion_dolares',
    'pinmueble',
    'pvehiculo',
    'pdatos_fiadores',
    'amonto_cancelar',
    'amonto_incobrable',
    'pmueble',
    'bgastos_proceso'
  ];

  private $varchar255Fields = ['pdespacho_judicial_juzgado', 'pdatos_codeudor2'];

  private $textFields = [
    'pdetalle_garantia',
    'pubicacion_garantia',
    'pcomentarios_bullet_point',
    'npartes_notificadas',
    'acolisiones_embargos_anotaciones',
    'ajustificacion_casos_protocolizados_embargo',
    'nanotaciones',
    'nubicacion_garantia',
    'ntalleres_situaciones',
    'ncomentarios',
    'acomentarios',
    'aregistro_pago',
    'atraspaso_tercero',
    'ttraspaso_favor_tercero',
    'tborrador_escritura',
    'tautorizacion_tercero',
    'rcausa',
    'dresultado_sentencia',
    'ames_avance_judicial',
    'pavance_cronologico',
    'lavance_cronologico',
    'savance_cronologico',
    'aavance_cronologico',
    'f1avance_cronologico',
    'f2avance_cronologico',
    'navance_cronologico'
  ];

  private $decimalFields = [
    'psaldo_de_seguros',
    'psaldo_de_multas',
    'pgastos_legales_caso',
    'nhonorarios_notificacion',
    'nhonorarios_cobro_administrativo',
    'thonorarios_traspaso',
    'tgastos_traspaso',
    'tgastos_legales',
    'thonorarios_totales',
    'fhonorarios_levantamiento',
    'fcomision_ccc',
    'fhonorarios_totales',
    'rhonorario_escritura_inscripcion',
    'rgastos_impuestos',
    'dgastos_microfilm',
    'dhonorarios',
    'bhonorarios_levantamiento',
    'bhonorarios_comision',
    'bhonorarios_totales',
    'f1honorarios_capturador',
    'f1honorarios_comision',
    'acarga_gastos_legales',
    'agastos_mas_honorarios_acumulados',
    'ahonorarios_iniciales',
    'adiferencia_demanda_presentada',
    'adiferencia_sentencia_afavor',
    'adiferencia_sentencia_enfirme',
    'adiferencia_liquidacion_de_sentencia_enfirme',
    'adiferencia_segunda_liquidacion_de_sentencia_enfirme',
    'adiferencia_tercera_liquidacion_de_sentencia_enfirme',
    'adiferencia_cuarta_liquidacion_de_sentencia_enfirme',
    'adiferencia_quinta_liquidacion_de_sentencia_enfirme',
    'adiferencia_sexta_liquidacion_de_sentencia_enfirme',
    'adiferencia_septima_liquidacion_de_sentencia_enfirme',
    'adiferencia_octava_liquidacion_de_sentencia_enfirme',
    'adiferencia_novena_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_primera_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_segunda_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_tercera_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_cuarta_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_quinta_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_sexta_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_septima_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_octava_liquidacion_de_sentencia_enfirme',
    'adiferencia_decima_novena_liquidacion_de_sentencia_enfirme',
    'agastos_legales_iniciales',
    'adiferencia_gastos_legales',
    'anumero_grupo',
    'pretenciones',
    'pmonto_prima',
    'pmonto_arreglo_pago',
    'pmonto_cuota',
    'honorarios_legales_dolares'
  ];

  private $intFields = ['pnumero', 'pexpectativa_recuperacion_id'];

  private $bigintFKFields = [
    'contact_id' => 'contacts,id',
    'bank_id' => 'banks,id',
    'product_id' => 'casos_productos,id',
    'proceso_id' => 'casos_procesos,id',
    'currency_id' => 'currencies,id',
    'abogado_id' => 'users,id',
    'asistente1_id' => 'users,id',
    'asistente2_id' => 'users,id',
    'aestado_proceso_general_id' => 'casos_estados,id',
    'testado_proceso_id' => 'casos_estados,id',
    'lestado_levantamiento_id' => 'casos_estados,id',
    'bestado_levantamiento_id' => 'casos_estados,id',
    'ddespacho_judicial_juzgado_id' => 'casos_juzgados,id',
    'ldespacho_judicial_juzgado_id' => 'casos_juzgados,id',
    'ppoderdante_id' => 'casos_poderdantes,id',
    'nestado_id' => 'casos_estados,id',
    'estado_id' => 'casos_estados,id',
  ];

  protected $listeners = [
    'datatableSettingChange' => 'refresDatatable',
    'dateRangeSelected' => 'dateRangeSelected',
  ];

  protected function getModelClass(): string
  {
    return Caso::class;
  }
}
