<?php

namespace App\Helpers;

use App\Models\Bank;

class ImportColumns
{

     /**
     * Normaliza los encabezados de columnas eliminando espacios,
     * caracteres invisibles y pasando todo a minúsculas.
     */
    public static function normalizeHeader($h)
    {
        return mb_strtolower(
            trim(
                str_replace("\xC2\xA0", ' ', (string) $h)
            )
        );
    }

    public const COLUMNAS_SANJOSE = [
        'Número'=> ['campo'=>'pnumero', 'tipo'=>'string'],
        'Cliente'=>['campo'=>'contact_id', 'tipo'=>'string'],
        'Producto' => ['campo' => 'product_id', 'tipo' => 'string'],
        'Proceso' => ['campo' => 'proceso_id', 'tipo' => 'string'],
        'Operación' => ['campo' => 'pnumero_operacion1', 'tipo' => 'string'],
        'Nombre' => ['campo' => 'pnombre_demandado', 'tipo' => 'string'],
        'Cédula' => ['campo' => 'pnumero_cedula', 'tipo' => 'string'],
        'Monto demanda' => ['campo' => 'pmonto_estimacion_demanda', 'tipo' => 'string'],
        'Moneda' => ['campo' => 'currency_id', 'tipo' => 'string'],
        'Expediente' => ['campo' => 'pnumero_expediente_judicial', 'tipo' => 'string'],
        'Estado Procesal' => ['campo' => 'aestado_proceso_general_id', 'tipo' => 'string'],
        'F. Asignación' => ['campo' => 'pfecha_asignacion_caso', 'tipo' => 'date'],
        'F. Demanda' => ['campo' => 'pfecha_presentacion_demanda', 'tipo' => 'date'],
        'F. Curso demanda' => ['campo' => 'pfecha_curso_demanda', 'tipo' => 'date'],
        'F. Notificación' => ['campo' => 'nfecha_notificacion_todas_partes', 'tipo' => 'date'],
        'F. 1° Giro' => ['campo' => 'pfecha_primer_giro', 'tipo' => 'date'],
        'F. Remate' => ['campo' => 'sfecha_remate', 'tipo' => 'date'],
        'F. Aprob. Remate' => ['campo' => 'afecha_aprobacion_remate', 'tipo' => 'date'],
        'F. Protocolización' => ['campo' => 'afecha_protocolizacion', 'tipo' => 'date'],
        'F. Puesta en Posesión' => ['campo' => 'afecha_senalamiento_puesta_posesion', 'tipo' => 'date'],
        'F. Arreglo P' => ['campo' => 'afecha_suspencion_arreglo', 'tipo' => 'date'],
        'Monto Retenc ¢' => ['campo' => 'pmonto_retencion_colones', 'tipo' => 'string'],
        'Monto Retenc $' => ['campo' => 'pmonto_retencion_dolares', 'tipo' => 'string'],
        'Inmueble' => ['campo' => 'pinmueble', 'tipo' => 'string'],
        'Vehículo' => ['campo' => 'pvehiculo', 'tipo' => 'string'],
        'F. Captura' => ['campo' => 'sfecha_captura', 'tipo' => 'date'],
        'F. Terminado' => ['campo' => 'afecha_terminacion', 'tipo' => 'date'],
        'Estatus de Operación' => ['campo' => 'pestatus_operacion', 'tipo' => 'string'],
        'Comentarios OCE' => ['campo' => 'ncomentarios', 'tipo' => 'string'],
        'Fecha de asignación al capturador' => ['campo' => 'f1fecha_asignacion_capturador', 'tipo' => 'date'],
        'Nombre del capturador' => ['campo' => 'capturador_id', 'tipo' => 'string'],
        'Servicio del Capturador' => ['campo' => 'caso_servicio_capturador_id', 'tipo' => 'string'],
        'Fecha de asignación al notificador' => ['campo' => 'f1fecha_asignacion_notificador', 'tipo' => 'date'],
        'Nombre del notificador' => ['campo' => 'notificador_id', 'tipo' => 'string'],
        'Servicio del Notificador' => ['campo' => 'caso_servicio_notificador_id', 'tipo' => 'string'],
        'Fecha de celebración de Primer remate'=>['campo'=>'sfecha_primer_remate', 'tipo'=>'date'],
        'Fecha de celebración de Segundo remate'=>['campo'=>'sfecha_segundo_remate', 'tipo'=>'date'],
        'Fecha de celebración de Tercer remate'=>['campo'=>'sfecha_tercer_remate', 'tipo'=>'date'],
    ];

    public const COLUMNAS_DAVIVIENDA = [
                        'Número'=> ['campo'=>'pnumero', 'tipo'=>'string'],
                        'Cliente'=>['campo'=>'contact_id', 'tipo'=>'string'],
                        'Fecha de Asignación de caso' => ['campo'=>'pfecha_asignacion_caso', 'tipo'=>'date'],
                        'Número Operación1'=>['campo'=>'pnumero_operacion1', 'tipo'=>'string'],
                        'Número Operación2'=>['campo'=>'pnumero_operacion2', 'tipo'=>'string'],
                        'Apellidos y Nombre del Deudor'=>['campo'=>'pnombre_apellidos_deudor', 'tipo'=>'string'],
                        'Cèdula deudor'=>['campo'=>'pcedula_deudor', 'tipo'=>'string'],
                        'Ente'=>['campo'=>'pente', 'tipo'=>'string'],
                        'Nombre de la Persona Jurídica'=>['campo'=>'pnombre_persona_juridica', 'tipo'=>'string'],
                        'Número de cédula jurídica'=>['campo'=>'pnumero_cedula_juridica', 'tipo'=>'string'],
                        'Datos Codeudor1 (Bullet Point)'=>['campo'=>'pdatos_codeudor1', 'tipo'=>'string'],
                        'Datos de los Fiadores'=>['campo'=>'pdatos_fiadores', 'tipo'=>'string'],
                        'Producto'=>['campo'=>'product_id', 'tipo'=>'string'],
                        'Tipo de Proceso'=>['campo'=>'proceso_id', 'tipo'=>'string'],
                        'Tipo de moneda'=>['campo'=>'currency_id', 'tipo'=>'string'],
                        'Expectativa Recuperación'=>['campo'=>'pexpectativa_recuperacion_id', 'tipo'=>'string'],
                        'Estatus de Operación'=>['campo'=>'pestatus_operacion', 'tipo'=>'string'],
                        'Número Expediente Judicial'=>['campo'=>'pnumero_expediente_judicial', 'tipo'=>'string'],
                        'Despacho Judicial Juzgado'=>['campo'=>'pdespacho_judicial_juzgado', 'tipo'=>'string'],
                        'Comprador'=>['campo'=>'pcomprador', 'tipo'=>'string'],
                        'Poderdante'=>['campo'=>'ppoderdante_id', 'tipo'=>'string'],
                        'Fecha de última gestión de cobro Administrativo'=>['campo'=>'pultima_gestion_cobro_administrativo', 'tipo'=>'date'],
                        'Fecha de ingreso a cobro judicial'=>['campo'=>'pfecha_ingreso_cobro_judicial', 'tipo'=>'date'],
                        'Fecha devolución de demanda para firma'=>['campo'=>'pfecha_devolucion_demanda_firma', 'tipo'=>'date'],
                        'Fecha de presentación de la demanda'=>['campo'=>'pfecha_presentacion_demanda', 'tipo'=>'date'],
                        'Fecha curso de la demanda'=>['campo'=>'pfecha_curso_demanda', 'tipo'=>'date'],
                        'Estado actual de la primera notificación de los demandados'=>['campo'=>'nestado_actual_primera_notificacion', 'tipo'=>'string'],
                        'Estado Proceso General'=>['campo'=>'aestado_proceso_general_id', 'tipo'=>'string'],
                        'Oposición de Demanda'=>['campo'=>'noposicion_demanda', 'tipo'=>'string'],
                        'Fecha de Audiencia'=>['campo'=>'nfecha_audiencia', 'tipo'=>'date'],
                        'Avance cronológico'=>['campo'=>'navance_cronologico', 'tipo'=>'string'],
                        'Fecha de Terminación'=>['campo'=>'afecha_terminacion', 'tipo'=>'date'],
                        'Tipo de Garantía'=>['campo'=>'ntipo_garantia', 'tipo'=>'string'],
                        'Detalle de la Garantía'=>['campo'=>'pdetalle_garantia', 'tipo'=>'string'],
                        'Embargos cuentas'=>['campo'=>'nembargos_cuentas', 'tipo'=>'string'],
                        'Embargos Salarios'=>['campo'=>'nembargos_salarios', 'tipo'=>'string'],
                        'Embargos Muebles'=>['campo'=>'nembargos_muebles', 'tipo'=>'string'],
                        'Embargos Inmuebles'=>['campo'=>'nembargos_inmuebles', 'tipo'=>'string'],
                        'Capturas'=>['campo'=>'sfecha_captura', 'tipo'=>'date'],
                        'Fecha de celebración de Primer remate'=>['campo'=>'sfecha_primer_remate', 'tipo'=>'date'],
                        'Fecha de celebración de Segundo remate'=>['campo'=>'sfecha_segundo_remate', 'tipo'=>'date'],
                        'Fecha de celebración de Tercer remate'=>['campo'=>'sfecha_tercer_remate', 'tipo'=>'date'],
                        'Fecha de firmeza de aprobación de remate'=>['campo'=>'afecha_firmeza_aprobacion_remate', 'tipo'=>'date'],
                        'Bienes Adjudicados'=>['campo'=>'abienes_adjudicados', 'tipo'=>'string'],
                        'Fecha señalamiento de puesta en posesión'=>['campo'=>'afecha_senalamiento_puesta_posesion', 'tipo'=>'date'],
                        'Puesta en posesión'=>['campo'=>'apuesta_posesion', 'tipo'=>'string'],
                        'Saldo Capital de la Operación Colones'=>['campo'=>'asaldo_capital_operacion', 'tipo'=>'string'],
                        'Saldo Capital de la Operación Dólares'=>['campo'=>'asaldo_capital_operacion_usd', 'tipo'=>'string'],
                        'Estimación de la Demanda en la Presentación Colones'=>['campo'=>'aestimacion_demanda_en_presentacion', 'tipo'=>'string'],
                        'Estimación de la Demanda en la Presentación Dólares'=>['campo'=>'aestimacion_demanda_en_presentacion_usd', 'tipo'=>'string'],
                        'Liquidacion de intereses aprobada Colones'=>['campo'=>'liquidacion_intereses_aprobada_crc', 'tipo'=>'string'],
                        'Liquidacion de intereses aprobada Dólares'=>['campo'=>'liquidacion_intereses_aprobada_usd', 'tipo'=>'string'],
                        'Gastos Legales'=>['campo'=>'agastos_legales', 'tipo'=>'string'],
                        'Honorarios totales Dólares'=>['campo'=>'ahonorarios_totales_usd', 'tipo'=>'string'],
                        'Honorarios totales Colones'=>['campo'=>'ahonorarios_totales', 'tipo'=>'string'],
                        'Bufete'=>['campo'=>'abufete', 'tipo'=>'string'],
                        'Tiempo en días'=>['campo'=>'tiempo_dias', 'tipo'=>'string'],
                        'Tiempo en años'=>['campo'=>'tiempo_annos', 'tipo'=>'string'],
                        'Retenciones'=>['campo'=>'pretenciones', 'tipo'=>'string'],
                        'Fecha de última liquidación'=>['campo'=>'nfecha_ultima_liquidacion', 'tipo'=>'date'],
                        'Monto Retenc Colones'=>['campo'=>'pmonto_retencion_colones', 'tipo'=>'string'],
                        'Monto Retenc Dólares'=>['campo'=>'pmonto_retencion_dolares', 'tipo'=>'string'],
                        'Fecha de activación'=>['campo'=>'fecha_activacion', 'tipo'=>'date'],
                        'Código de activación'=>['campo'=>'codigo_activacion', 'tipo'=>'string'],
                        'Fecha de asignación al capturador' => ['campo' => 'f1fecha_asignacion_capturador', 'tipo' => 'date'],
                        'Nombre del capturador' => ['campo' => 'capturador_id', 'tipo' => 'string'],
                        'Servicio del Capturador' => ['campo' => 'caso_servicio_capturador_id', 'tipo' => 'string'],
                        'Fecha de asignación al notificador' => ['campo' => 'f1fecha_asignacion_notificador', 'tipo' => 'date'],
                        'Nombre del notificador' => ['campo' => 'notificador_id', 'tipo' => 'string'],
                        'Servicio del Notificador' => ['campo' => 'caso_servicio_notificador_id', 'tipo' => 'string'],
                    ];

    public const COLUMNAS_SCOTIABANKCR = [
        'Número'=> ['campo'=>'pnumero', 'tipo'=>'string'],
        'Cliente'=>['campo'=>'contact_id', 'tipo'=>'string'],
        'Número Operación1'=>['campo'=>'pnumero_operacion1', 'tipo'=>'string'],
        'Producto'=>['campo'=>'product_id', 'tipo'=>'string'],
        'PROCESO'=>['campo'=>'proceso_id', 'tipo'=>'string'],
        'Nombre del Demandado'=>['campo'=>'pnombre_demandado', 'tipo'=>'string'],
        'Número de Cédula del demandado'=>['campo'=>'pnumero_cedula', 'tipo'=>'string'],
        'MONEDA'=>['campo'=>'currency_id', 'tipo'=>'string'],
        'Monto Estimación Demanda'=>['campo'=>'pmonto_estimacion_demanda', 'tipo'=>'string'],
        'Firma Legal'=>['campo'=>'afirma_legal', 'tipo'=>'string'],
        'Fecha Asignación de Caso'=>['campo'=>'pfecha_asignacion_caso', 'tipo'=>'date'],
        'Fecha Presentación Demanda'=>['campo'=>'pfecha_presentacion_demanda', 'tipo'=>'date'],
        'Fecha Traslado Juzgado'=>['campo'=>'nfecha_traslado_juzgado', 'tipo'=>'date'],
        'Fecha Captura'=>['campo'=>'sfecha_captura', 'tipo'=>'date'],
        'Fecha Notificación Todas las Partes'=>['campo'=>'nfecha_notificacion_todas_partes', 'tipo'=>'date'],
        'Fecha Remate'=>['campo'=>'sfecha_remate', 'tipo'=>'date'],
        'Fecha Aprobación de Remate'=>['campo'=>'afecha_aprobacion_remate', 'tipo'=>'date'],
        'Fecha de Registro'=>['campo'=>'afecha_registro', 'tipo'=>'date'],
        'Fecha Presentación Protocolización'=>['campo'=>'afecha_presentacion_protocolizacion', 'tipo'=>'date'],
        'Fecha de Inscripción'=>['campo'=>'afecha_inscripcion', 'tipo'=>'date'],
        'Fecha aprovación levantamientos'=>['campo'=>'afecha_levantamiento', 'tipo'=>'date'],
        'Fecha de Terminación'=>['campo'=>'afecha_terminacion', 'tipo'=>'date'],
        'Fecha Suspención Arreglo'=>['campo'=>'afecha_suspencion_arreglo', 'tipo'=>'date'],
        'Justificación Casos Protocolizados Embargo'=>['campo'=>'ajustificacion_casos_protocolizados_embargo', 'tipo'=>'string'],
        'Estado Proceso General'=>['campo'=>'aestado_proceso_general_id', 'tipo'=>'string'],
        'Número Expediente Judicial'=>['campo'=>'pnumero_expediente_judicial', 'tipo'=>'string'],
        'Despacho Judicial Juzgado'=>['campo'=>'pdespacho_judicial_juzgado', 'tipo'=>'string'],
        'Fecha de informe'=>['campo'=>'pfecha_informe', 'tipo'=>'date'],
        'Avance cronológico'=>['campo'=>'pavance_cronologico', 'tipo'=>'string'],
        'Tipo Expediente'=>['campo'=>'atipo_expediente', 'tipo'=>'string'],
        'Reasignaciones'=>['campo'=>'areasignaciones', 'tipo'=>'string'],
        'Fecha de inicio de retenciones'=>['campo'=>'fecha_inicio_retenciones', 'tipo'=>'date'],
        'Fecha de Prescripción'=>['campo'=>'fecha_prescripcion', 'tipo'=>'date'],
        'Fecha de Pruebas'=>['campo'=>'fecha_pruebas', 'tipo'=>'date'],
        'Motivo de Terminación'=>['campo'=>'motivo_terminacion', 'tipo'=>'string'],
        'Honorarios Legales Dólares'=>['campo'=>'honorarios_legales_dolares', 'tipo'=>'string'],
        'Fecha de asignación al capturador' => ['campo' => 'f1fecha_asignacion_capturador', 'tipo' => 'date'],
        'Nombre del capturador' => ['campo' => 'capturador_id', 'tipo' => 'string'],
        'Servicio del Capturador' => ['campo' => 'caso_servicio_capturador_id', 'tipo' => 'string'],
        'Fecha de asignación al notificador' => ['campo' => 'f1fecha_asignacion_notificador', 'tipo' => 'date'],
        'Nombre del notificador' => ['campo' => 'notificador_id', 'tipo' => 'string'],
        'Servicio del Notificador' => ['campo' => 'caso_servicio_notificador_id', 'tipo' => 'string'],
        'Fecha de celebración de Primer remate'=>['campo'=>'sfecha_primer_remate', 'tipo'=>'date'],
        'Fecha de celebración de Segundo remate'=>['campo'=>'sfecha_segundo_remate', 'tipo'=>'date'],
        'Fecha de celebración de Tercer remate'=>['campo'=>'sfecha_tercer_remate', 'tipo'=>'date'],
    ];


    public const COLUMNAS_TERCEROS = [
        'Número'=> ['campo'=>'pnumero', 'tipo'=>'string'],
        'Cliente'=>['campo'=>'contact_id', 'tipo'=>'string'],
        'SUBCIDIARIA'=>['campo'=>'psubsidiaria', 'tipo'=>'string'],
        'TIPO PRODUCTO'=>['campo'=>'product_id', 'tipo'=>'string'],
        'PROCESO'=>['campo'=>'proceso_id', 'tipo'=>'string'],
        'Nombre del Demandado'=>['campo'=>'pnombre_demandado', 'tipo'=>'string'],
        'Número de Cédula del demandado'=>['campo'=>'pnumero_cedula', 'tipo'=>'string'],
        'MONEDA'=>['campo'=>'currency_id', 'tipo'=>'string'],
        'DETALLE DE GARANTÍA O DOCUMENTO'=>['campo'=>'pdetalle_garantia', 'tipo'=>'string'],
        'Despacho Judicial Juzgado'=>['campo'=>'pdespacho_judicial_juzgado', 'tipo'=>'string'],
        'Número Expediente Judicial'=>['campo'=>'pnumero_expediente_judicial', 'tipo'=>'string'],
        'Monto Estimación Demanda'=>['campo'=>'pmonto_estimacion_demanda', 'tipo'=>'string'],
        'INMUEBLES'=>['campo'=>'pinmueble', 'tipo'=>'string'],
        'MUEBLES'=>['campo'=>'pmueble', 'tipo'=>'string'],
        'Fecha Presentación Demanda'=>['campo'=>'pfecha_presentacion_demanda', 'tipo'=>'date'],
        'Fecha Asignación de Caso'=>['campo'=>'pfecha_asignacion_caso', 'tipo'=>'date'],
        'Fecha Traslado Juzgado'=>['campo'=>'nfecha_traslado_juzgado', 'tipo'=>'date'],
        'Fecha Notificación Todas las Partes'=>['campo'=>'nfecha_notificacion_todas_partes', 'tipo'=>'date'],
        'FECHA DE PRESENTACIO DE EMBARGO'=>['campo'=>'afecha_presentacion_embargo', 'tipo'=>'date'],
        'FECHA ARREGLO DE PAGO'=>['campo'=>'afecha_arreglo_pago', 'tipo'=>'date'],
        'Expectativa Recuperación'=>['campo'=>'pexpectativa_recuperacion_id', 'tipo'=>'string'],
        'GESTIONES - AVANCE CRONOLÓGICO'=>['campo'=>'pavance_cronologico', 'tipo'=>'string'],
        'COMENTARIOS'=>['campo'=>'acomentarios', 'tipo'=>'string'],
        'Estado Proceso General'=>['campo'=>'aestado_proceso_general_id', 'tipo'=>'string'],
        'Tipo Expediente'=>['campo'=>'atipo_expediente', 'tipo'=>'string'],
        'Fechas de pago'=>['campo'=>'afecha_pago', 'tipo'=>'date'],
        'Monto que debe cancelar'=>['campo'=>'amonto_cancelar', 'tipo'=>'string'],
        'Monto Incobrable'=>['campo'=>'amonto_incobrable', 'tipo'=>'string'],
        'Contacto telefónico'=>['campo'=>'acontacto_telefonico', 'tipo'=>'string'],
        'Correo electrónico'=>['campo'=>'acorreo', 'tipo'=>'string'],
        'Fecha de asignación al capturador' => ['campo' => 'f1fecha_asignacion_capturador', 'tipo' => 'date'],
        'Nombre del capturador' => ['campo' => 'capturador_id', 'tipo' => 'string'],
        'Servicio del Capturador' => ['campo' => 'caso_servicio_capturador_id', 'tipo' => 'string'],
        'Fecha de asignación al notificador' => ['campo' => 'f1fecha_asignacion_notificador', 'tipo' => 'date'],
        'Nombre del notificador' => ['campo' => 'notificador_id', 'tipo' => 'string'],
        'Servicio del Notificador' => ['campo' => 'caso_servicio_notificador_id', 'tipo' => 'string'],
        'Fecha de celebración de Primer remate'=>['campo'=>'sfecha_primer_remate', 'tipo'=>'date'],
        'Fecha de celebración de Segundo remate'=>['campo'=>'sfecha_segundo_remate', 'tipo'=>'date'],
        'Fecha de celebración de Tercer remate'=>['campo'=>'sfecha_tercer_remate', 'tipo'=>'date'],
    ];

    public const COLUMNAS_LAFISE = [
        'Número'=> ['campo'=>'pnumero', 'tipo'=>'string'],
        'Cliente'=>['campo'=>'contact_id', 'tipo'=>'string'],
        'Número Operación1'=>['campo'=>'pnumero_operacion1', 'tipo'=>'string'],
        'Número de Tarjeta'=>['campo'=>'pnumero_tarjeta', 'tipo'=>'string'],
        'Nombre del Demandado'=>['campo'=>'pnombre_demandado', 'tipo'=>'string'],
        'Número de Cédula del demandado'=>['campo'=>'pnumero_cedula', 'tipo'=>'string'],
        'Nombre de la Persona Jurídica'=>['campo'=>'pnombre_persona_juridica', 'tipo'=>'string'],
        'Número de cédula Jurídica'=>['campo'=>'pnumero_cedula_juridica', 'tipo'=>'string'],
        'Datos Codeudor1 (Bullet Point)'=>['campo'=>'pdatos_codeudor1', 'tipo'=>'string'],
        'Datos de los Fiadores'=>['campo'=>'pdatos_codeudor2', 'tipo'=>'string'],
        'PRODUCTO'=>['campo'=>'product_id', 'tipo'=>'string'],
        'Tipo de Proceso'=>['campo'=>'proceso_id', 'tipo'=>'string'],
        'Tipo de moneda'=>['campo'=>'currency_id', 'tipo'=>'string'],
        'Expectativa Recuperación'=>['campo'=>'pexpectativa_recuperacion_id', 'tipo'=>'string'],
        'Estatus de Operación'=>['campo'=>'aestado_operacion', 'tipo'=>'string'],
        'Número Expediente Judicial'=>['campo'=>'pnumero_expediente_judicial', 'tipo'=>'string'],
        'Despacho Judicial Juzgado'=>['campo'=>'pdespacho_judicial_juzgado', 'tipo'=>'string'],
        'Comprador'=>['campo'=>'pcomprador', 'tipo'=>'string'],
        'Poderdante'=>['campo'=>'ppoderdante_id', 'tipo'=>'string'],
        'Fecha de ingreso a cobro judicial'=>['campo'=>'pfecha_ingreso_cobro_judicial', 'tipo'=>'date'],
        'Fecha de escrito de demanda'=>['campo'=>'pfecha_escrito_demanda', 'tipo'=>'date'],
        'Fecha de presentación de la demanda'=>['campo'=>'pfecha_presentacion_demanda', 'tipo'=>'date'],
        'Fecha Traslado Juzgado'=>['campo'=>'nfecha_traslado_juzgado', 'tipo'=>'date'],
        'Fecha de finalización del proceso'=>['campo'=>'afecha_terminacion', 'tipo'=>'date'],
        'Fecha de notificaciones de las partes'=>['campo'=>'nfecha_notificacion_todas_partes', 'tipo'=>'date'],
        'ESTADO'=>['campo'=>'nestado_id', 'tipo'=>'string'],
        'Estado Proceso General'=>['campo'=>'aestado_proceso_general_id', 'tipo'=>'string'],
        'Oposición de Demanda'=>['campo'=>'noposicion_demanda', 'tipo'=>'string'],
        'Fecha de Audiencia'=>['campo'=>'nfecha_audiencia', 'tipo'=>'date'],
        'Fecha Informe última Gestión'=>['campo'=>'afecha_informe_ultima_gestion', 'tipo'=>'date'],
        'Avance cronológico'=>['campo'=>'pavance_cronologico', 'tipo'=>'string'],
        'Tipo de Garantía'=>['campo'=>'ntipo_garantia', 'tipo'=>'string'],
        'Detalle de la Garantía'=>['campo'=>'pdetalle_garantia', 'tipo'=>'string'],
        'Monto Avaluo'=>['campo'=>'amonto_avaluo', 'tipo'=>'string'],
        'Fecha avaluo'=>['campo'=>'afecha_avaluo', 'tipo'=>'date'],
        'Embargos cuentas'=>['campo'=>'aembargo_cuentas', 'tipo'=>'string'],
        'Embargos Salarios'=>['campo'=>'aembargo_salarios', 'tipo'=>'string'],
        'Embargos Muebles'=>['campo'=>'aembargo_muebles', 'tipo'=>'string'],
        'Embargos Inmuebles'=>['campo'=>'aembargo_inmuebles', 'tipo'=>'string'],
        'Retenciones con giro'=>['campo'=>'aretenciones_con_giro', 'tipo'=>'string'],
        'Fecha de último giro'=>['campo'=>'afecha_ultimo_giro', 'tipo'=>'date'],
        'Capturas'=>['campo'=>'sfecha_captura', 'tipo'=>'date'],
        'Fecha de celebración de Primer remate'=>['campo'=>'sfecha_primer_remate', 'tipo'=>'date'],
        'Fecha de celebración de Segundo remate'=>['campo'=>'sfecha_segundo_remate', 'tipo'=>'date'],
        'Fecha de celebración de Tercer remate'=>['campo'=>'sfecha_tercer_remate', 'tipo'=>'date'],
        'Fecha de firmeza de aprobación de remate'=>['campo'=>'afecha_aprobacion_remate', 'tipo'=>'date'],
        'Bienes Adjudicados'=>['campo'=>'abienes_adjudicados', 'tipo'=>'string'],
        'Fecha señalamiento de puesta en posesión'=>['campo'=>'afecha_senalamiento_puesta_posesion', 'tipo'=>'date'],
        'Puesta en posesión'=>['campo'=>'apuesta_posesion', 'tipo'=>'string'],
        'Saldo Capital de la Operación'=>['campo'=>'asaldo_capital_operacion', 'tipo'=>'string'],
        'Estimación en colones de la Demanda en la Presentación'=>['campo'=>'pmonto_estimacion_demanda_colones', 'tipo'=>'string'],
        'Estimación en dólares de la Demanda en la Presentación'=>['campo'=>'pmonto_estimacion_demanda_dolares', 'tipo'=>'string'],
        'Estimación dolarizada de la Demanda en la Presentación'=>['campo'=>'psaldo_dolarizado', 'tipo'=>'string'],
        'Gastos Legales'=>['campo'=>'agastos_legales', 'tipo'=>'string'],
        'Honorarios totales'=>['campo'=>'ahonorarios_totales', 'tipo'=>'string'],
        'Bufete'=>['campo'=>'abufete', 'tipo'=>'string'],
        'Fecha de asignación al capturador' => ['campo' => 'f1fecha_asignacion_capturador', 'tipo' => 'date'],
        'Nombre del capturador' => ['campo' => 'capturador_id', 'tipo' => 'string'],
        'Servicio del Capturador' => ['campo' => 'caso_servicio_capturador_id', 'tipo' => 'string'],
        'Fecha de asignación al notificador' => ['campo' => 'f1fecha_asignacion_notificador', 'tipo' => 'date'],
        'Nombre del notificador' => ['campo' => 'notificador_id', 'tipo' => 'string'],
        'Servicio del Notificador' => ['campo' => 'caso_servicio_notificador_id', 'tipo' => 'string'],
    ];

    public const COLUMNAS_FINANCIERACAFSA = [
        'Número'=> ['campo'=>'pnumero', 'tipo'=>'string'],
        'Cliente'=>['campo'=>'contact_id', 'tipo'=>'string'],
        'Número de operación'=>['campo'=>'pnumero_operacion1', 'tipo'=>'string'],
        'Apellidos y Nombre del Deudor'=>['campo'=>'pnombre_demandado', 'tipo'=>'string'],
        'Documento de Identificación'=>['campo'=>'pnumero_cedula', 'tipo'=>'string'],
        'Tipo de Proceso'=>['campo'=>'proceso_id', 'tipo'=>'string'],
        'PRODUCTO'=>['campo'=>'product_id', 'tipo'=>'string'],
        'Número de expediente'=>['campo'=>'pnumero_expediente_judicial', 'tipo'=>'string'],
        'Despacho Judicial'=>['campo'=>'pdespacho_judicial_juzgado', 'tipo'=>'string'],
        'Fecha de ingreso a cobro judicial'=>['campo'=>'pfecha_ingreso_cobro_judicial', 'tipo'=>'date'],
        'Fecha Escrito de demanda'=>['campo'=>'pfecha_escrito_demanda', 'tipo'=>'date'],
        'Fecha de presentación de la demanda'=>['campo'=>'pfecha_presentacion_demanda', 'tipo'=>'date'],
        'Estado actual de la notificación de los demandados y anotantes'=>['campo'=>'nestado_id', 'tipo'=>'string'],
        'Etapa Procesal'=>['campo'=>'aestado_proceso_general_id', 'tipo'=>'string'],
        'FECHA DE TERMINACION'=>['campo'=>'afecha_terminacion', 'tipo'=>'date'],
        'Estado ID'=>['campo'=>'pestadoid', 'tipo'=>'string'],
        'Avances en orden cronológico del proceso'=>['campo'=>'pavance_cronologico', 'tipo'=>'string'],
        'Detalle de la Garantía'=>['campo'=>'pdetalle_garantia', 'tipo'=>'string'],
        'Fecha de Captura'=>['campo'=>'sfecha_captura', 'tipo'=>'date'],
        'Fecha de celebración de Primer remate'=>['campo'=>'sfecha_primer_remate', 'tipo'=>'date'],
        'Fecha de celebración de Segundo remate'=>['campo'=>'sfecha_segundo_remate', 'tipo'=>'date'],
        'Fecha de celebración de Tercer remate'=>['campo'=>'sfecha_tercer_remate', 'tipo'=>'date'],
        'Fecha de firmeza de aprobación de remate'=>['campo'=>'afecha_aprobacion_remate', 'tipo'=>'date'],
        'Moneda'=>['campo'=>'currency_id', 'tipo'=>'string'],
        'Estimación de la demanda'=>['campo'=>'pmonto_estimacion_demanda', 'tipo'=>'string'],
        'Saldo Capital de la Operación'=>['campo'=>'asaldo_capital_operacion', 'tipo'=>'string'],
        'Probabilidad de recuperación'=>['campo'=>'pexpectativa_recuperacion_id', 'tipo'=>'string'],
        'Mes de avance judicial'=>['campo'=>'ames_avance_judicial', 'tipo'=>'string'],
        'Fecha de asignación al capturador' => ['campo' => 'f1fecha_asignacion_capturador', 'tipo' => 'date'],
        'Nombre del capturador' => ['campo' => 'capturador_id', 'tipo' => 'string'],
        'Servicio del Capturador' => ['campo' => 'caso_servicio_capturador_id', 'tipo' => 'string'],
        'Fecha de asignación al notificador' => ['campo' => 'f1fecha_asignacion_notificador', 'tipo' => 'date'],
        'Nombre del notificador' => ['campo' => 'notificador_id', 'tipo' => 'string'],
        'Servicio del Notificador' => ['campo' => 'caso_servicio_notificador_id', 'tipo' => 'string'],
    ];

    public const COLUMNAS_BANCOGENERAL = [
        'Número'=> ['campo'=>'pnumero', 'tipo'=>'string'],
        'Cliente'=>['campo'=>'contact_id', 'tipo'=>'string'],
        'Número Operación1'=>['campo'=>'pnumero_operacion1', 'tipo'=>'string'],
        'Nombre del Demandado'=>['campo'=>'pnombre_demandado', 'tipo'=>'string'],
        'Producto'=>['campo'=>'product_id', 'tipo'=>'string'],
        'Proceso'=>['campo'=>'proceso_id', 'tipo'=>'string'],
        'Despacho Judicial Juzgado'=>['campo'=>'pdespacho_judicial_juzgado', 'tipo'=>'string'],
        'Número Expediente Judicial'=>['campo'=>'pnumero_expediente_judicial', 'tipo'=>'string'],
        'Estado'=>['campo'=>'nestado_id', 'tipo'=>'string'],
        'Estado Proceso General'=>['campo'=>'aestado_proceso_general_id', 'tipo'=>'string'],
        'Avance cronológico'=>['campo'=>'pavance_cronologico', 'tipo'=>'string'],
        'DETALLE DE LA GARANTIA'=>['campo'=>'pdetalle_garantia', 'tipo'=>'string'],
        'Fecha de Remate 1'=>['campo'=>'sfecha_primer_remate', 'tipo'=>'date'],
        'Fecha de Remate 2'=>['campo'=>'sfecha_segundo_remate', 'tipo'=>'date'],
        'Fecha de Remate 3'=>['campo'=>'sfecha_tercer_remate', 'tipo'=>'date'],
        'Bien adjudicado #'=>['campo'=>'abienes_adjudicados', 'tipo'=>'string'],
        'Moneda'=>['campo'=>'currency_id', 'tipo'=>'string'],
        'Monto Estimación Demanda'=>['campo'=>'pmonto_estimacion_demanda', 'tipo'=>'string'],
        'ESTIMACION DE GASTOS'=>['campo'=>'bgastos_proceso', 'tipo'=>'string'],
        'Fecha de Terminación'=>['campo'=>'afecha_terminacion', 'tipo'=>'date'],
        'Fecha de asignación al capturador' => ['campo' => 'f1fecha_asignacion_capturador', 'tipo' => 'date'],
        'Nombre del capturador' => ['campo' => 'capturador_id', 'tipo' => 'string'],
        'Servicio del Capturador' => ['campo' => 'caso_servicio_capturador_id', 'tipo' => 'string'],
        'Fecha de asignación al notificador' => ['campo' => 'f1fecha_asignacion_notificador', 'tipo' => 'date'],
        'Nombre del notificador' => ['campo' => 'notificador_id', 'tipo' => 'string'],
        'Servicio del Notificador' => ['campo' => 'caso_servicio_notificador_id', 'tipo' => 'string'],
    ];

    //Bank::BANCODECOSTARICA => self::COLUMNAS_BANCODECOSTARICA,
    //Bank::SCOTIABANKBCH => self::COLUMNAS_SCOTIABANKBCH,

    public static function getColumnasPorBanco($banco)
    {
        // Mapeo de bancos por ID y por nombre
        $map = [
          Bank::SCOTIABANKCR => self::COLUMNAS_SCOTIABANKCR,
          Bank::TERCEROS => self::COLUMNAS_TERCEROS,
          Bank::LAFISE => self::COLUMNAS_LAFISE,
          Bank::DAVIVIENDA => self::COLUMNAS_DAVIVIENDA,
          Bank::SANJOSE => self::COLUMNAS_SANJOSE,
          Bank::FINANCIERACAFSA => self::COLUMNAS_FINANCIERACAFSA,
          Bank::BANCOGENERAL => self::COLUMNAS_BANCOGENERAL,
          //Bank::BANCODECOSTARICA => self::COLUMNAS_BANCODECOSTARICA,
          Bank::SCOTIABANKBCH => self::COLUMNAS_SCOTIABANKCR,
          Bank::COOCIQUE => self::COLUMNAS_TERCEROS,
        ];

        // Si es un string, convertir a mayúsculas para coincidencias
        if (is_string($banco)) {
            $banco = strtoupper(trim($banco));
            // Buscar coincidencia por nombre
            return $map[$banco] ?? [];
        }

        // Si es numérico, buscar directamente en el map
        if (is_int($banco) || ctype_digit((string)$banco)) {
            return $map[(int)$banco] ?? [];
        }

        // Si no coincide, devolver array vacío
        return [];
    }
}
